### ISSUE TITLE
Maaany issues

### ISSUE THREAD

**Issue by scionae** [AVnetWS/Hentoid#137] opened 2017-08-26 09:48 UTC
Okay so what's happening basically:
1. I can't save my files into external storage (Operation not allowed!)
2. I can't download anything from Tsumino
3. When I download some big file (like Let Your Smile Bloom on Hentai Cafe) at around 40-50% of the download the app refreshes itself and I have to download the doujin again, resulting in a loop.
4. I can't download most doujin on the various sites, the button just breaks (like in Tsumino)

So, there are the issues, if you need anything else and a more in-depth analysis, I can provide everything to help this app get better, good luck! ^^

**Comment by avluis** [comment] 2017-08-26 10:36
I need logCat...

Here is the issue template:

Please fill in the below fields with some data to help us best diagnose the issue.
The more specific you are, the better! You can help a lot by not making us ask these questions.
Feel free to remove any irrelevant parts that you know are not related to the issue.
Any HTML comment like this will be stripped when rendering markdown, no need to delete them.
If an issue does not have the following template filled out, it will be closed without discussion.

What version of Hentoid you're running, for example: 1.2.0r3 | 1.2.1r1 | 1.2.1r2
It's essentially the version number from the About Screen
**Hentoid Version**:

What devices you managed to get the issue to come up on? For example:
fails on Galaxy S4/GT-I9500 4.4.2, works fine on Nexus 6P 5.1 and Genymotion Nexus 5 5.0.1
**Device/Android Version**:

Share the details of your issue in prose, detailing actual and expected behavior.
**Issue details / Repro steps**:

What is the error message that you got in the log?
**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

Bonus points if you attach a relevant screenshot or a screen recording

**Comment by avluis** [comment] 2017-10-18 20:28
@scionae Closing due to non-interest

**Closed by avluis** 2017-10-18 20:28 UTC
